server:
  port: 7001
#  servlet:
#    context-path: /eureka  这个有啥用

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com # Eureka服务端实例的名字
  client:
    register-with-eureka: false  # 表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果为false，则表示自己为注册中心
    service-url: # 监控页面地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#        单机模式http://${eureka.instance.hostname}:${server.port}/eureka/
