# 应用名称
#spring:
#  application:
#    name: springboot
# 应用服务 WEB 访问端口
server:
  port: 9090
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.dly.springboot.mybatis.entity
# 数据源名称
#  spring.datasource.name=defaultDataSource
# 数据库驱动：
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/longge?serverTimezone=GMT%2b8
    username: root
    password: 123456

#配置输出sql语句
mybatis:
  mapper-locations: classpath:mapper/*.xml  #    如果不加这个配置，springboot不知道mapper文件夹的存在，会报错500 -- "Internal Server Error"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
